spring:
  application:
    name: micromarket

  datasource:
    url: jdbc:mysql://localhost:3306/micro_market_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Cambiado de 'create' a 'update' para evitar pérdida de datos, create borra y crea la base de datos cada vez, vslidation para validar las entidades con la base de datos, update solo actualiza la estructura sin borrar datos
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

server:
  port: 8080
  error:
      include-message: always

security:
  jwt:
    secret-key: my-super-secure-jwt-secret-key-change-this-please-2026
    token-expiration: 86400000